import { HttpException, Injectable } from '@nestjs/common'
import { randomBytes } from 'node:crypto'
import { PrismaService } from '../prisma.service'
const fail=(s:number,c:string,m:string):never=>{throw new HttpException({error:{code:c,message:m,details:null}},s)}
const string=(v:unknown)=>typeof v==='string'?v:undefined; const int=(v:unknown)=>typeof v==='number'&&Number.isInteger(v)?v:undefined
@Injectable() export class AdminService {
 constructor(private readonly prisma:PrismaService){}
 categories(restaurantId:string){return this.prisma.menuCategory.findMany({where:{restaurantId},orderBy:{sortOrder:'asc'}})}
 async createCategory(restaurantId:string,b:Record<string,unknown>){const name=string(b.name),sortOrder=int(b.sortOrder);if(!name||sortOrder===undefined)fail(400,'VALIDATION_ERROR','Danh mục không hợp lệ.');return this.prisma.menuCategory.create({data:{restaurantId,name:name!,sortOrder:sortOrder!}})}
 async updateCategory(restaurantId:string,id:string,b:Record<string,unknown>){const found=await this.prisma.menuCategory.findFirst({where:{id,restaurantId}});if(!found)fail(404,'CATEGORY_NOT_FOUND','Không tìm thấy danh mục.');return this.prisma.menuCategory.update({where:{id},data:{...(string(b.name)?{name:string(b.name)}:{}),...(int(b.sortOrder)!==undefined?{sortOrder:int(b.sortOrder)}:{}),...(typeof b.isActive==='boolean'?{isActive:b.isActive}:{})}})}
 async deleteCategory(restaurantId:string,id:string){if(await this.prisma.menuItem.count({where:{restaurantId,categoryId:id,deletedAt:null}}))fail(409,'CATEGORY_NOT_EMPTY','Danh mục vẫn còn món.');const deleted=await this.prisma.menuCategory.deleteMany({where:{id,restaurantId}});if(!deleted.count)fail(404,'CATEGORY_NOT_FOUND','Không tìm thấy danh mục.');return {id}}
 items(restaurantId:string,categoryId?:string){return this.prisma.menuItem.findMany({where:{restaurantId,deletedAt:null,...(categoryId?{categoryId}:{})},orderBy:{sortOrder:'asc'}})}
 async createItem(restaurantId:string,b:Record<string,unknown>){const categoryId=string(b.categoryId),name=string(b.name),priceVnd=int(b.priceVnd),sortOrder=int(b.sortOrder);if(!categoryId||!name||priceVnd===undefined||sortOrder===undefined)fail(400,'VALIDATION_ERROR','Món không hợp lệ.');if(!await this.prisma.menuCategory.findFirst({where:{id:categoryId,restaurantId}}))fail(404,'CATEGORY_NOT_FOUND','Không tìm thấy danh mục.');return this.prisma.menuItem.create({data:{restaurantId,categoryId:categoryId!,name:name!,priceVnd:priceVnd!,sortOrder:sortOrder!,description:string(b.description)??null,imageUrl:string(b.imageUrl)??null}})}
 async updateItem(restaurantId:string,id:string,b:Record<string,unknown>){const found=await this.prisma.menuItem.findFirst({where:{id,restaurantId}});if(!found)fail(404,'ITEM_NOT_FOUND','Không tìm thấy món.');const categoryId=string(b.categoryId);if(categoryId&&!await this.prisma.menuCategory.findFirst({where:{id:categoryId,restaurantId}}))fail(404,'CATEGORY_NOT_FOUND','Không tìm thấy danh mục.');return this.prisma.menuItem.update({where:{id},data:{...(categoryId?{categoryId}:{}),...(string(b.name)?{name:string(b.name)}:{}),...(int(b.priceVnd)!==undefined?{priceVnd:int(b.priceVnd)}:{}),...(int(b.sortOrder)!==undefined?{sortOrder:int(b.sortOrder)}:{}),...(typeof b.description==='string'||b.description===null?{description:b.description}:{}),...(typeof b.imageUrl==='string'||b.imageUrl===null?{imageUrl:b.imageUrl}:{}),...(typeof b.isAvailable==='boolean'?{isAvailable:b.isAvailable}:{})}})}
 async deleteItem(restaurantId:string,id:string){const changed=await this.prisma.menuItem.updateMany({where:{id,restaurantId},data:{deletedAt:new Date()}});if(!changed.count)fail(404,'ITEM_NOT_FOUND','Không tìm thấy món.');return {id}}
 async tables(restaurantId:string){const tables=await this.prisma.diningTable.findMany({where:{restaurantId},orderBy:{sortOrder:'asc'}});const base=process.env.GUEST_BASE_URL??'http://localhost:5173';return {tables:tables.map(t=>({...t,qrUrl:`${base}/t/${t.qrToken}`}))}}
 async createTable(restaurantId:string,b:Record<string,unknown>){const code=string(b.code),displayName=string(b.displayName),sortOrder=int(b.sortOrder);if(!code||!displayName||sortOrder===undefined)fail(400,'VALIDATION_ERROR','Bàn không hợp lệ.');const qrToken=randomBytes(18).toString('base64url');return this.prisma.diningTable.create({data:{restaurantId,code:code!,displayName:displayName!,sortOrder:sortOrder!,qrToken}})}
 async updateTable(restaurantId:string,id:string,b:Record<string,unknown>){const found=await this.prisma.diningTable.findFirst({where:{id,restaurantId}});if(!found)fail(404,'TABLE_NOT_FOUND','Không tìm thấy bàn.');return this.prisma.diningTable.update({where:{id},data:{...(string(b.code)?{code:string(b.code)}:{}),...(string(b.displayName)?{displayName:string(b.displayName)}:{}),...(int(b.sortOrder)!==undefined?{sortOrder:int(b.sortOrder)}:{}),...(typeof b.isActive==='boolean'?{isActive:b.isActive}:{})}})}
 async deleteTable(restaurantId:string,id:string){if(await this.prisma.tableSession.count({where:{restaurantId,tableId:id,status:'OPEN'}}))fail(409,'TABLE_HAS_OPEN_SESSION','Bàn đang có khách.');const deleted=await this.prisma.diningTable.deleteMany({where:{id,restaurantId}});if(!deleted.count)fail(404,'TABLE_NOT_FOUND','Không tìm thấy bàn.');return {id}}
 restaurant(restaurantId:string){return this.prisma.restaurant.findUniqueOrThrow({where:{id:restaurantId}})}
 async staffPairing(restaurantId:string){const restaurant=await this.prisma.restaurant.findUniqueOrThrow({where:{id:restaurantId},select:{staffLoginCode:true}});const base=(process.env.STAFF_BASE_URL??'http://staff.tableqr.localhost:8080').replace(/\/$/,'');return {staffPairingUrl:`${base}/pair/${encodeURIComponent(restaurant.staffLoginCode)}`}}
 async updateRestaurant(restaurantId:string,b:Record<string,unknown>){return this.prisma.restaurant.update({where:{id:restaurantId},data:{...(string(b.name)?{name:string(b.name)}:{}),...(typeof b.logoUrl==='string'||b.logoUrl===null?{logoUrl:b.logoUrl}:{}),...(typeof b.address==='string'||b.address===null?{address:b.address}:{})}})}
}
