import { type MenuCategory } from '@kimthanh-tableqr/contracts'
import { Button, EmptyState, ErrorState, IconButton, LoadingSkeleton, Modal } from '@kimthanh-tableqr/ui'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { GripVertical, Pencil, Plus, Power, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { useAdminAuth } from '../features/auth/auth-context'
import { createCategory, deleteCategory, getCategories, getItems, updateCategory } from '../lib/api/admin'

export function MenuPage() {
  const { auth } = useAdminAuth(); const client = useQueryClient(); const [editing, setEditing] = useState<MenuCategory | null | undefined>(); const [deleting, setDeleting] = useState<MenuCategory | null>(null); const [error, setError] = useState(''); const [dragged, setDragged] = useState<string | null>(null)
  const categories = useQuery({ queryKey: ['admin-categories'], queryFn: () => getCategories(auth!.token) }); const items = useQuery({ queryKey: ['admin-items'], queryFn: () => getItems(auth!.token) })
  const refresh = () => { void client.invalidateQueries({ queryKey: ['admin-categories'] }); void client.invalidateQueries({ queryKey: ['admin-items'] }) }
  async function save(name: string) { const trimmed = name.trim(); if (!trimmed) { setError('Tên danh mục là bắt buộc.'); return }; try { if (editing) await updateCategory(auth!.token, editing.id, { name: trimmed }); else await createCategory(auth!.token, { name: trimmed, sortOrder: categories.data?.categories.length ?? 0 }); setEditing(undefined); setError(''); refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể lưu danh mục.') } }
  async function toggle(category: MenuCategory) { try { await updateCategory(auth!.token, category.id, { isActive: !category.isActive }); refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể cập nhật danh mục.') } }
  async function remove() { if (!deleting) return; try { await deleteCategory(auth!.token, deleting.id); setDeleting(null); refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể xóa danh mục.') } }
  async function drop(target: MenuCategory) { if (!dragged || dragged === target.id || !categories.data) return; const ordered = [...categories.data.categories]; const from = ordered.findIndex((category) => category.id === dragged); const to = ordered.findIndex((category) => category.id === target.id); const [moved] = ordered.splice(from, 1); if (!moved) return; ordered.splice(to, 0, moved); setDragged(null); try { await Promise.all(ordered.map((category, index) => updateCategory(auth!.token, category.id, { sortOrder: index }))); refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể đổi thứ tự.') } }
  if (categories.isPending || items.isPending) return <div className="admin-menu"><LoadingSkeleton height={360} width="100%" /></div>
  if (categories.error || items.error) return <ErrorState action={<Button onClick={refresh} variant="secondary">Thử lại</Button>} description="Không tải được thực đơn." title="Đã có lỗi" />
  const count = (id: string) => items.data!.items.filter((item) => item.categoryId === id).length
  return <div className="admin-menu"><header><div><h1>Thực đơn</h1><p>Danh mục và món đang phục vụ</p></div><Button onClick={() => setEditing(null)}><Plus size={18} />Danh mục</Button></header>{error ? <p className="admin-menu__error" role="alert">{error}</p> : null}<div className="admin-menu__layout"><section className="admin-panel"><header><h2>Danh mục</h2></header>{categories.data!.categories.length ? categories.data!.categories.map((category) => <div className={category.isActive ? 'admin-category' : 'admin-category admin-category--inactive'} draggable key={category.id} onDragOver={(event) => event.preventDefault()} onDragStart={() => setDragged(category.id)} onDrop={() => void drop(category)}><GripVertical aria-hidden="true" size={18}/><span><b>{category.name}</b><small>{count(category.id)} món</small></span><button aria-label={`Bật tắt ${category.name}`} onClick={() => void toggle(category)} type="button"><Power size={16}/></button><IconButton aria-label={`Sửa ${category.name}`} icon={<Pencil size={16}/>} onClick={() => setEditing(category)}/><IconButton aria-label={`Xóa ${category.name}`} icon={<Trash2 size={16}/>} onClick={() => setDeleting(category)} variant="danger"/></div>) : <EmptyState title="Chưa có danh mục" description="Thêm danh mục đầu tiên để bắt đầu."/>}</section><section className="admin-panel admin-menu__items"><header><h2>Danh sách món</h2><span>Chọn danh mục để xem món</span></header></section></div><CategoryModal category={editing} error={error} key={editing?.id ?? (editing === null ? 'new' : 'closed')} onClose={() => { setEditing(undefined); setError('') }} onSave={save}/><Modal actions={<><Button onClick={() => setDeleting(null)} variant="secondary">Không</Button><Button onClick={() => void remove()} variant="danger">Xóa danh mục</Button></>} description="Danh mục còn món sẽ không thể xóa. Hãy chuyển hoặc xóa các món trước." isOpen={Boolean(deleting)} onClose={() => setDeleting(null)} title={deleting ? `Xóa “${deleting.name}”?` : ''}/></div>
}
function CategoryModal({ category, error, onClose, onSave }: { readonly category: MenuCategory | null | undefined; readonly error: string; readonly onClose: () => void; readonly onSave: (name: string) => void }) { const [name, setName] = useState(category?.name ?? ''); return <Modal actions={<><Button onClick={onClose} variant="secondary">Hủy</Button><Button onClick={() => onSave(name)}>Lưu</Button></>} isOpen={category !== undefined} onClose={onClose} title={category ? 'Sửa danh mục' : 'Thêm danh mục'}><label className="admin-field"><span>Tên danh mục</span><input autoFocus onChange={(event) => setName(event.target.value)} value={name}/>{error ? <small>{error}</small> : null}</label></Modal> }
