import { Button, ErrorState, LoadingSkeleton } from '@kimthanh-tableqr/ui'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Printer } from 'lucide-react'
import { QRCodeCanvas } from 'qrcode.react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAdminAuth } from '../features/auth/auth-context'
import { getTables } from '../lib/api/admin'

export function PrintPage() { const { auth } = useAdminAuth(); const navigate = useNavigate(); const tables = useQuery({ queryKey:['admin-tables'], queryFn:()=>getTables(auth!.token) }); const [selected,setSelected] = useState<Set<string> | null>(null); if(tables.isPending)return <div className="admin-print-loading"><LoadingSkeleton height={500} width="100%"/></div>; if(tables.error)return <ErrorState action={<Button onClick={()=>void tables.refetch()} variant="secondary">Thử lại</Button>} title="Không tải được bàn"/>; const active=tables.data!.tables.filter(table=>table.isActive); const chosen=selected??new Set(active.map(table=>table.id)); const printable=active.filter(table=>chosen.has(table.id)); const pages=Array.from({length:Math.ceil(printable.length/12)},(_,index)=>printable.slice(index*12,index*12+12)); const toggle=(id:string)=>setSelected(current=>{const next=new Set(current??active.map(table=>table.id));if(next.has(id))next.delete(id);else next.add(id);return next}); return <div className="admin-print"><header className="admin-print__bar"><h1>In mã QR cho bàn</h1><span>{printable.length} bàn · {pages.length||0} trang A4</span><Button onClick={()=>navigate('/tables')} variant="secondary"><ArrowLeft size={17}/>Quay lại</Button><Button onClick={()=>window.print()}><Printer size={17}/>In</Button></header><div className="admin-print__select"><strong>Chọn bàn cần in</strong>{active.map(table=><label key={table.id}><input checked={chosen.has(table.id)} onChange={()=>toggle(table.id)} type="checkbox"/>{table.displayName}</label>)}</div><main className="admin-print__stage">{pages.map((page,index)=><section className="admin-print__sheet" key={index}>{page.map(table=><article className="admin-print__cell" key={table.id}><span className="admin-print__shop">KIM THÀNH</span><QRCodeCanvas includeMargin level="M" size={120} value={table.qrUrl}/><strong>{table.displayName}</strong><small>Quét mã để xem thực đơn và gọi món</small></article>)}</section>)}</main></div> }
