import { Button, EmptyState, LoadingSkeleton, Modal, ToastRegion } from '@kimthanh-tableqr/ui'
import { formatRelativeTime, formatTime, formatVnd, minutesSince, primaryActionLabel, primaryNextStatus, type OrderStatus, type StaffOrderDto } from '@kimthanh-tableqr/contracts'
import { MoreHorizontal } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useStaffAuth } from '../features/auth/auth-context'
import { simulateStaffOrder, updateStaffOrder } from '../lib/api/staff'
import { useOrderStream } from '../lib/realtime'
import { useSound } from '../features/sound/sound-context'
const columns: Array<{status: Extract<OrderStatus,'NEW'|'PREPARING'|'SERVED'>; title:string}>=[{status:'NEW',title:'Đơn mới'},{status:'PREPARING',title:'Đang làm'},{status:'SERVED',title:'Đã phục vụ'}]
export function OrdersPage(){const {auth}=useStaffAuth();const stream=useOrderStream();const {notify}=useSound();const known=useRef(new Set<string>());const fresh=useRef(new Set<string>());const [cancel,setCancel]=useState<StaffOrderDto|null>(null);const [message,setMessage]=useState<string|null>(null);useEffect(()=>{stream.orders.forEach(o=>{if(known.current.size&&!known.current.has(o.id)){fresh.current.add(o.id);notify()}known.current.add(o.id)});const t=window.setTimeout(()=>fresh.current.clear(),3000);return()=>window.clearTimeout(t)},[notify,stream.orders]);async function change(order:StaffOrderDto,status:OrderStatus){if(!auth)return;stream.replaceOrder({...order,status});try{stream.replaceOrder(await updateStaffOrder(auth.token,order.id,status))}catch{stream.replaceOrder(order);setMessage('Không thể cập nhật đơn. Vui lòng thử lại.');stream.refetch()}}if(stream.isLoading)return <div className="staff-orders"><h1>Đơn hàng</h1><LoadingSkeleton height={220} width="100%"/></div>;if(!stream.orders.length)return <EmptyState description="Đơn của khách sẽ hiện ở đây." title="Chưa có đơn nào"/>;return <div className="staff-orders"><h1>Đơn hàng</h1><div className="staff-order-columns">{columns.map(c=>{const list=stream.orders.filter(o=>o.status===c.status).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));return <section key={c.status}><header className="staff-order-column__title"><h2>{c.title}</h2><span>{list.length}</span></header>{list.length?list.map(o=><OrderCard fresh={fresh.current.has(o.id)} key={o.id} onCancel={()=>setCancel(o)} onChange={s=>void change(o,s)} order={o}/>):<div className="staff-order-column__empty">Chưa có đơn nào</div>}</section>})}</div>{import.meta.env.VITE_USE_MOCK==='true'?<button className="staff-simulate" onClick={()=>auth&&void simulateStaffOrder(auth.token).then(stream.refetch)} type="button">+ Giả lập đơn mới</button>:null}<Modal actions={<><Button onClick={()=>setCancel(null)} variant="secondary">Không</Button><Button onClick={()=>{if(cancel)void change(cancel,'CANCELLED');setCancel(null)}} variant="danger">Hủy đơn</Button></>} description="Đơn sẽ không được tính vào tổng tiền của bàn." isOpen={Boolean(cancel)} onClose={()=>setCancel(null)} title={cancel?`Hủy đơn ${cancel.table.displayName}?`:''}/><ToastRegion toasts={message?[{id:'order-error',message}]:[]}/></div>}
function OrderCard({fresh,onCancel,onChange,order}:{readonly fresh:boolean;readonly onCancel:()=>void;readonly onChange:(s:OrderStatus)=>void;readonly order:StaffOrderDto}){const late=order.status==='NEW'&&minutesSince(order.createdAt)>10;const next=primaryNextStatus(order.status);const label=primaryActionLabel(order.status);return <article className={`staff-order-card ${fresh?'staff-order-card--fresh':''}`}><header><strong>{order.table.displayName}</strong><span>lần gọi #{order.sequenceNo}</span></header><p className={late?'staff-order-card__late':''}>{formatTime(order.createdAt)} · {formatRelativeTime(order.createdAt)}{late?' · quá lâu':''}</p><div>{order.items.map(i=><section key={i.id}><b>{i.quantity}×</b><span><strong>{i.nameSnapshot}</strong>{i.note?<small>↳ {i.note}</small>:null}</span></section>)}</div><footer><strong>{formatVnd(order.totalVnd)}</strong>{next&&label?<button onClick={()=>onChange(next)} type="button">{label}</button>:null}{next?<button aria-label="Hủy đơn" className="staff-order-card__more" onClick={onCancel} type="button"><MoreHorizontal size={20}/></button>:null}</footer></article>}
