import { API_BASE_PATH, type AuthResponse, type CloseSessionResponse, type OrderStatus, type PaySessionResponse, type StaffOrderDto, type StaffOrdersResponse, type StaffSessionDetailResponse, type StaffTablesResponse } from '@kimthanh-tableqr/contracts'
export async function loginStaff(pin: string): Promise<AuthResponse> { const response = await fetch(`${API_BASE_PATH}/staff/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pin }) }); if (!response.ok) throw new Error('Mã PIN không đúng. Thử lại.'); return response.json() as Promise<AuthResponse> }
export async function getStaffOrders(token: string, since?: string): Promise<StaffOrdersResponse> { const query = since ? `?since=${encodeURIComponent(since)}` : ''; const response = await fetch(`${API_BASE_PATH}/staff/orders${query}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Không tải được đơn bếp.'); return response.json() as Promise<StaffOrdersResponse> }
export async function simulateStaffOrder(token: string): Promise<void> { const response = await fetch(`${API_BASE_PATH}/__debug/staff/orders`, { method:'POST', headers:{ Authorization:`Bearer ${token}` } }); if (!response.ok) throw new Error('Không tạo được đơn mô phỏng.'); }
export async function updateStaffOrder(token: string, id: string, status: OrderStatus): Promise<StaffOrderDto> { const response = await fetch(`${API_BASE_PATH}/staff/orders/${id}/status`, { method:'PATCH', headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}, body:JSON.stringify({status}) }); if (!response.ok) throw new Error('Không thể cập nhật đơn.'); return response.json() as Promise<StaffOrderDto> }
export async function getStaffTables(token:string):Promise<StaffTablesResponse>{const response=await fetch(`${API_BASE_PATH}/staff/tables`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Không tải được sơ đồ bàn.');return response.json() as Promise<StaffTablesResponse>}
export async function getStaffSession(token:string,id:string):Promise<StaffSessionDetailResponse>{const r=await fetch(`${API_BASE_PATH}/staff/sessions/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Không tải được phiên bàn.');return r.json() as Promise<StaffSessionDetailResponse>}
export async function paySession(token:string,id:string):Promise<PaySessionResponse>{const r=await fetch(`${API_BASE_PATH}/staff/sessions/${id}/pay`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Không thể ghi nhận thanh toán.');return r.json() as Promise<PaySessionResponse>}
export async function closeSession(token:string,id:string):Promise<CloseSessionResponse>{const r=await fetch(`${API_BASE_PATH}/staff/sessions/${id}/close`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Không thể reset bàn.');return r.json() as Promise<CloseSessionResponse>}
